### PR TITLE
Fix #19

### LINKED ISSUE #19: FileExistsError
`FileExistsError: [Errno 17] File exists: 'output/audioClips/ru'` when dubbing for the same language again with `genAudio` set to `False`, which is the default for `genAudio`

### PR DESCRIPTION
**Pull request by aruseni**

### CODE REVIEW

**Comment by aruseni** [comment]
@googlebot I signed it!

**Comment by dalequark** [comment]
Hey aruseni, thanks for contributing. Could you give me some context on this? Not sure I see the error. Also, would you mind adding a commit message and removing formatting diffs from the commit?

Thanks!

**Comment by aruseni** [comment]
@dalequark Thanks for your awesome work. :)
I’ve changed my commit.
It solves #19. The problem is `os.mkdir(languageDir)` that gives you a `FileExistsError` if you already have a dir for a particular language and you did not set `genAudio` to `False`, so you want to regenerate the audio.

**Comment by aruseni** [comment]
@dalequark Thanks for your awesome work. :)
I’ve changed my commit.
It solves #19. The problem is `os.mkdir(languageDir)` that gives you a `FileExistsError` if you already have a dir for a particular language and you did not set `genAudio` to `True`, so you want to just reuse the existing audio if it’s available.

**Comment by dalequark** [comment]
Merged--thank you @aruseni !

**Pull request merged**
